# Reference - https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  GitHubOrg:
    Type: String
    Default: xplorer-io
  OIDCProviderArn:
    Type: String
    Description: Arn for the GitHub OIDC Provider.
    Default: ""

Conditions:
  CreateOIDCProvider: !Equals
    - !Ref OIDCProviderArn
    - ""

Resources:

  GithubAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Allow github actions to assume this role to deploy resources to AWS
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - CreateOIDCProvider
                - !Ref GithubOidc
                - !Ref OIDCProviderArn
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/*
      Policies:
        - PolicyName: GithubActionsPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - lambda:GetFunction
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:InvokeFunction
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:ListTags
                  - lambda:TagResource
                  - lambda:UntagResource
                  - lambda:PutFunctionEventInvokeConfig
                  - lambda:DeleteFunctionEventInvokeConfig
                  - lambda:ListVersionsByFunction
                  - lambda:GetFunctionCodeSigningConfig
                  - lambda:GetPolicy
                Resource:
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:xplorers*
              - Effect: Allow
                Action:
                  - lambda:DeleteLayerVersion
                  - lambda:GetLayerVersion
                  - lambda:PublishLayerVersion
                Resource:
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:xplorers*
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource:
                  - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/xplorers*
                  - !Sub arn:aws:cloudformation:${AWS::Region}:aws:transform/*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetObjectTagging
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:DeleteObjectTagging
                  - s3:DeleteObjectVersion
                  - s3:DeleteObjectVersionTagging
                  - s3:DeleteObject
                Resource:
                  - arn:aws:s3:::xplorers-artifact-bucket
                  - arn:aws:s3:::xplorers-artifact-bucket/*
              - Effect: Allow
                Action:
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:CreateRole
                  - iam:GetPolicy
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:CreatePolicy
                  - iam:DeleteRole
                  - iam:DetachRolePolicy
                  - iam:UpdateRole
                  - iam:DeleteRolePolicy
                  - iam:PutRolePolicy
                  - iam:CreatePolicyVersion
                  - iam:DeletePolicyVersion
                  - iam:DeletePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - iam:ListInstanceProfilesForRole
                  - iam:TagRole
                  - iam:UntagRole
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/xplorers*
                  - !Sub arn:aws:iam::${AWS::AccountId}:policy/xplorers*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:DescribeLogGroups
                  - logs:PutLogEvents
                  - logs:TagResource
                  - logs:PutRetentionPolicy
                  - logs:DeleteRetentionPolicy
                  - logs:ListTagsLogGroup
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/xplorers*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group::log-stream*
              - Effect: Allow
                Action:
                  - apigateway:PUT
                  - apigateway:PATCH
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:DELETE
                  - apigateway:UpdateRestApiPolicy
                Resource:
                  - !Sub arn:aws:apigateway:${AWS::Region}::/restapis*
                  - !Sub arn:aws:apigateway:${AWS::Region}::/tags*
              - Effect: Allow
                Action:
                  - events:DescribeRule
                  - events:PutTargets
                  - events:RemoveTargets
                  - events:DeleteRule
                  - events:PutRule
                  - events:ListTagsForResource
                  - events:TagResource
                  - events:UntagResource
                  - events:ListTargetsByRule
                Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/xplorers*

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd

Outputs:
  GithubAssumeRoleArn:
    Value: !GetAtt GithubAssumeRole.Arn
